### ISSUE TITLE
Participants, Managers, & Leaders Needed (please comment here)

### ISSUE THREAD

**Issue by Kacem78** [daveshap/raven#51]
Hi Folks, I'm Kacem from France, AI engineer, my thesis  was on 1987,  i'm now acting as a speaker, evangelizer and teacher 
if any need, i m glad to help and contribute

**Comment by neilaconway** [comment]
Hello all, I am Neil Andrew and I am primarily a systems integration engineer and programmer. I have my BSCIS and have worked in programming across a variety of platforms, languages, and countries. I have been getting into AI/ML recently and have built a few small projects. I am a former FIRST robotics programming mentor with almost 25-30 years of programming / dba / systems dev & analysis / audio engineering / and the like. I hope to participate.

**Comment by kevinwpage** [comment]
Hi Everyone. My name is Kevin Page and I am an entrepreneur, angel investor and creative with a couple of years as an Ai tool power-user under my belt. My main focus for many years has been to combine technology with the human artmaking process. I hold four US patents on a robotics and software platform for empowering pointillist oil painting on an epic scale (some of our paintings were as large as 8'x6' and included over 1/2 million individual strokes of oil paint!) I also own an Ai-live-action filmmaking company that has invented several proprietary workflows that combine various currently available Ai tools with traditional filmmaking techniques. We currently have 3 films in competition on the international film festival circuit.

As a business leader, I have formed (and exited) two start-ups in the specialty financial services sector and have raised capital for a number of others as a licensed investment banker (retired). I have run several small development teams (as the client) and generally like to gain a broad view and understanding of the projects I engage with...which I suppose makes me a generalist of sorts? One of my talents is to take very complex subjects and communicate them in a simple, clear fashion using language and images that make the information accessible to the general public. 

On this project, I have been putting in those "general understanding" hours in by reading David's books and following along with the development of this early Raven community on Github. It has been a GREAT learning experience and I invite everyone who has the time to do the BG research on this project to do so. (Only one of David's books is over two hundred pages and they are all clearly written and super-helpful!) I will probably be most useful (at least until we get to MVP) on the media/communications team, finance and fund-raising, business development and partnerships, and general governance. I am also a power tester and breaker-of-code!

My latest self-improvement project has been to study up on consensus decision making protocols (Consensus Through Conversation by L. Dressler is a VERY good read on the subject) in anticipation of helping facilitate some of our group decision making processes where needed.

That being said, I am open to almost any assignment (other than slinging code) where I have a useful skill set.

I am glad to be here and a part of this amazingly smart and diverse group! Let me know if you need anything. I'm always open to new challenges!

**Comment by Aadish01** [comment]
Hello everyone I am Aadish undergrad. engineering student from India. I have worked on C++ and Python. I have been following David in YouTube for a while and I would love to contribute anything to RAVEN.

**Comment by timfoote** [comment]
@neilaconway @kevinwpage @Aadish01 thank you for the intros!  Great to have you on board.  Just a little housekeeping thing - can you add your intros to the discussion #3 ?  This issue here appears to have been created in error and I'm going to close it.

Thanks!
