### ISSUE TITLE
Participants, Managers, & Leaders Needed (please comment here)

### ISSUE THREAD

**Issue by neilaconway** [daveshap/raven#61]
### Discussed in https://github.com/daveshap/raven/discussions/3

<div type='discussions-op-text'>

<sup>Originally posted by **daveshap** February  1, 2023</sup>
Hey everyone, this project will be too big for me to do myself. I've had numerous people reach out on LinkedIn and Patreon already but I'd like to consolidate here. Basically, we need a few different kinds of folks helping out. 

- Community managers. These are folks who serve as the social glue, making sure people get messages, contacts get updated, organize calls and meetings, and moderate content.
- Leaders. These are folks familiar with Agile, DevOps, and/or OSS who can provide some oversight and guidance to the project
- Engineers. These are folks who can help sling code. Ranging from Python experts to full stack devs, and devops engineers.

Please comment if you're one of these!</div>

**Comment by neilaconway** [comment]
Hello all, I am Neil Andrew and I am primarily a systems integration engineer and programmer. I have my BSCIS and have worked in programming across a variety of platforms, languages, and countries. I have been getting into AI/ML recently and have built a few small projects. I am a former FIRST robotics programming mentor with almost 25-30 years of programming / dba / systems dev & analysis / audio engineering / and the like. I hope to participate.

**Comment by timfoote** [comment]
@neilaconway welcome, did you intend on opening this issue for any particular reason?  if not, please close it :)
